choco install -y awscli
choco install -y azure-cli
choco install -y doctl
choco install -y terraform
choco install -y cyberduck
choco install -y mremoteng
choco install -y vagrant
choco install -y packer
choco install -y vault
choco install -y kubernetes-cli
